#!/bin/bash

MAIN=src/vitamin.nim
BIN=bin/vita
NIMFLAGS="--hints:off --experimental:notnil"

case $1 in
clean)
	rm -r bin
;;
setup)
	nimble install noise patty
;;
run)
	shift
	nim r $NIMFLAGS $MAIN $@
;;
profile)
	shift
	nim r -d:profile --profiler:on --stacktrace:on $NIMFLAGS $MAIN $@
;;
test)
	shift
	BIN=bin/vita-test
	echo "BUILD $BIN"
	nim c -o:$BIN $NIMFLAGS $MAIN || exit $?
	for f in test/standalone/[^X]*.v; do
		echo "file $f (no prelude)"
		$BIN -P $@ $f
	done
	for f in test/[^X]*.v; do
		echo "file $f"
		$BIN $@ $f
	done
	rm $BIN
;;
release)
	shift
	mkdir -p `dirname $BIN`
	nim c -o:$BIN -d:release --opt:speed --passC:"-Ofast" $NIMFLAGS $MAIN
;;
*)
	mkdir -p `dirname $BIN`
	nim c -o:$BIN -d:release --opt:speed --passC:"-Ofast -march=native" $NIMFLAGS $MAIN
;;
esac
