#!/bin/sh

MAIN=src/vitamin.nim
BIN=bin/vita
NIMFLAGS="--hints:off"

case $1 in
clean)
	rm -r bin
;;
setup)
	nimble install noise
;;
run)
	shift
	nim r $NIMFLAGS $MAIN $@
;;
release)
	shift
	mkdir -p bin
	nim c -o:$BIN -d:release --opt:speed --passC:"-Ofast" $NIMFLAGS $MAIN
;;
*)
	mkdir -p bin
	nim c -o:$BIN --opt:speed --passC:"-Ofast -march=native" $NIMFLAGS $MAIN
;;
esac

