<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>v</string>
      <string>vita</string>
    </array>
    <key>name</key>
    <string>Vitamin</string>
    <key>scopeName</key>
    <string>source.v</string>
    <key>uuid</key>
    <string>b5a8b312-87b3-45e7-9258-7a3e50d1af3b</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>keyword.control.vitamin</string>
        <key>match</key>
        <string>\b(let|var|use|use-syntax|use-macro|use-implicit|fun|test|assert|opaque|Lazy|Quoted|Expand|Args|undefined|unreachable)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>storage.modifier.vitamin</string>
        <key>match</key>
        <string>\b(tag|imm|mut|rd|wr)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.other.vitamin</string>
        <key>match</key>
        <string>\b(do|if|elif|else|while|for|case|of|defer|guard|pass|label|jump|block|with|where|return|continue|break|quote|shift|reset)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>storage.type.vitamin</string>
        <key>match</key>
        <string>\b(Type|Unit|None|Bool|Any|Never|Union|Inter|Record|Variant|Enum|Module|Array|List|Set|Map|Ptr|Str|Int|Size|Float|I8|I16|I32|I64|U8|U16|U32|U64|F32|F64)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.block.vitamin</string>
        <key>begin</key>
        <string>#\[</string>
        <key>end</key>
        <string>]#</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.vitamin</string>
        <key>match</key>
        <string>#.*$
?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.arrow.vitamin</string>
        <key>match</key>
        <string>=\&gt;|-\&gt;|\&lt;-</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.vitamin</string>
        <key>match</key>
        <string>\b(is|as|in)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.logical.vitamin</string>
        <key>match</key>
        <string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.logical.vitamin</string>
        <key>match</key>
        <string>\b(not|and|or|xor)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.vitamin</string>
        <key>match</key>
        <string>(:=|:|=|==|!=|&lt;=|&gt;=|&lt;|&gt;|-|\+|\*|\||&amp;|\?|\?\?|\$|\$\$)|((?&lt;=[^\.])\.\.\.(?=[^\.]))|((?&lt;=[^\.])\.(?=[^\.]))</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.vitamin</string>
        <key>match</key>
        <string>\b(div|mod)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>variable.language.vitamin</string>
        <key>match</key>
        <string>\b(self|\$[0-9]+)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type.vitamin</string>
        <key>match</key>
        <string>\b[A-Z][A-Za-z0-9_-]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>entity.name.varaible</string>
        <key>match</key>
        <string>\b[@]?[A-Za-z_][A-Za-z0-9_-]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.separator.comma.vitamin</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.separator.semicolon.vitamin</string>
        <key>match</key>
        <string>;</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.decimal.vitamin</string>
        <key>match</key>
        <string>\b-?[0-9]+(\.[0-9]+)?[A-Za-z]*\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.octal.vitamin</string>
        <key>match</key>
        <string>\b-?0o[0-7]+\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.hex.vitamin</string>
        <key>match</key>
        <string>\b-?0x[0-9A-Fa-f]+\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.bin.vitamin</string>
        <key>match</key>
        <string>\b-?0b[01]+\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.block.vitamin</string>
        <key>begin</key>
        <string>"""</string>
        <key>end</key>
        <string>"""</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.block.vitamin</string>
        <key>begin</key>
        <string>'''</string>
        <key>end</key>
        <string>'''</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.vitamin</string>
        <key>match</key>
        <string>"(\.|[^"])*"</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.single.vitamin</string>
        <key>match</key>
        <string>'(\.|[^\'])*'</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.single.vitamin</string>
        <key>match</key>
        <string>`.*`</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.vitamin</string>
        <key>match</key>
        <string>\b(true|false|none)\b</string>
      </dict>
    </array>
  </dict>
</plist>